name: Dependency Tree

on: [push]

jobs:
  dependency-tree:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Dependency Tree for Maven
      uses: advanced-security/maven-dependency-submission-action@v3
      with:
        directory: .
